// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sf.Server.Data.Sf;

#nullable disable

namespace sf.Server.Data.Migrations
{
    [DbContext(typeof(SfContext))]
    [Migration("20250124085514_import")]
    partial class import
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("sf.Server.Models.Core.Entity<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<bool>("Imported")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Entity<Guid>");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("sf.Server.Models.SF.ClassModel", b =>
                {
                    b.HasBaseType("sf.Server.Models.Core.Entity<System.Guid>");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("sf.Server.Models.SF.DisciplineModel", b =>
                {
                    b.HasBaseType("sf.Server.Models.Core.Entity<System.Guid>");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.ToTable("Disciplines", (string)null);
                });

            modelBuilder.Entity("sf.Server.Models.SF.TeamModel", b =>
                {
                    b.HasBaseType("sf.Server.Models.Core.Entity<System.Guid>");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasIndex("DisciplineId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("sf.Server.Models.SF.UserModel", b =>
                {
                    b.HasBaseType("sf.Server.Models.Core.Entity<System.Guid>");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DisciplineModelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.HasIndex("ClassId");

                    b.HasIndex("DisciplineModelId");

                    b.HasIndex("TeamId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("sf.Server.Models.SF.ClassModel", b =>
                {
                    b.HasOne("sf.Server.Models.Core.Entity<System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("sf.Server.Models.SF.ClassModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sf.Server.Models.SF.DisciplineModel", b =>
                {
                    b.HasOne("sf.Server.Models.Core.Entity<System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("sf.Server.Models.SF.DisciplineModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sf.Server.Models.SF.TeamModel", b =>
                {
                    b.HasOne("sf.Server.Models.SF.DisciplineModel", "Discipline")
                        .WithMany("Teams")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sf.Server.Models.Core.Entity<System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("sf.Server.Models.SF.TeamModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("sf.Server.Models.SF.UserModel", b =>
                {
                    b.HasOne("sf.Server.Models.SF.ClassModel", "Class")
                        .WithMany("Users")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sf.Server.Models.SF.DisciplineModel", null)
                        .WithMany("Students")
                        .HasForeignKey("DisciplineModelId");

                    b.HasOne("sf.Server.Models.Core.Entity<System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("sf.Server.Models.SF.UserModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sf.Server.Models.SF.TeamModel", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("sf.Server.Models.SF.ClassModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("sf.Server.Models.SF.DisciplineModel", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("sf.Server.Models.SF.TeamModel", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
